language: cpp
compiler:
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq devscripts build-essential equivs python-software-properties
notifications:
  slack: cocaine:qDewv6ZVDt0TciQeNdE47GqG
script: "tests/ci/travis.sh"
