language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq devscripts build-essential equivs python-software-properties
script: "tests/ci/travis.sh"
